fos_user: 
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"

filmapp:
    resource: "@FilmappBundle/Controller/"
    type:     annotation
    prefix:   /
    
#    
#app:
#    resource: "@AppBundle/Controller/"
#    type:     annotation
#    prefix:   /
#    

